### ISSUE TITLE
无法正常获取漫画正文

### ISSUE THREAD

**Issue by WenHe233** [FrothierNine346/crawler-terra-historicus#1]
使用操作系统：windows10
使用python版本：3.9.1
报错说明：
在执行python main.py时，出现报错

> H:\github\crawler-terra-historicus>python main.py
罗德岛源石记事——莱茵生命:   0%|                         | 0/10 [00:00<?, ?it/s罗德岛源石记事——莱茵生命:   0%|                         | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "H:\github\crawler-terra-historicus\main.py", line 141, in <module>
    TH.save_data()
  File "H:\github\crawler-terra-historicus\main.py", line 118, in save_data
    if upgrade_time >= old_time:
UnboundLocalError: local variable 'upgrade_time' referenced before assignment

只能获取到“罗德岛源石记事——莱茵生命”的封面和info.txt
![image](https://user-images.githubusercontent.com/43093562/177264005-a31d4c6b-be6e-474b-8615-116f77ba74d1.png)

再次执行时显示“罗德岛源石记事——莱茵生命”已是最新，但是所有文件夹中还是只有封面和info.txt

> H:\github\crawler-terra-historicus>python main.py
罗德岛源石记事——莱茵生命已经是最新
罗德厨房——回甘:   0%|                                    | 0/2 [00:00<?, ?it/s罗德厨房——回甘: 100%|████████████████████████████████████| 2/2 [00:00<?, ?it/s]
A1行动预备组: 100%|██████████████████████████████████████| 3/3 [00:00<?, ?it/s]
123罗德岛！？: 100%|███████████████████████████████████| 27/27 [00:00<?, ?it/s]
罗德岛源石记事——黑钢:   0%|                             | 0/10 [00:00<?, ?it/s罗德岛源石记事——黑钢: 100%|████████████████████████████| 10/10 [00:00<?, ?it/s]
罗德岛闲逛部: 100%|████████████████████████████████████| 21/21 [00:00<?, ?it/s]
罗德岛相簿: 100%|█████████████████████████████| 60/60 [00:00<00:00, 114.62it/s]

![image](https://user-images.githubusercontent.com/43093562/177265041-2d4ad37e-9e41-4875-9bbc-247b32837201.png)

**Comment by FrothierNine346** [comment]
已修复，请删除info.txt后重试。
